### ISSUE TITLE
Suggestion: Config option to move display

### ISSUE THREAD

**Issue by SoopCanSam** [Kesomannen/PingDisplay#1]
It would be nice to be able to adjust where the latency displays on screen using LethalConfig. Since with steam the fps display can overlap and with the PerformanceEnhancer mod showing the FPS up there too they overlap. 

https://thunderstore.io/c/lethal-company/p/Solar32/PerformanceEnhancer/

**Comment by Kesomannen** [comment]
Will do

**Comment by Kesomannen** [comment]
Added DisplayPosition config in 1.1.0

**Comment by SoopCanSam** [comment]
Sweet thanks. You may want to update the changelog on ThunderStore and possibly the description. Most people won't go searching in the GutHub issues before deciding if they want to try it or not.
