### ISSUE TITLE
[Question] LC using UDP, can i know how u can ping the latency?

### ISSUE THREAD

**Issue by CoolLKKPS** [Kesomannen/PingDisplay#2]
same as topic
i always got 0 ms no matter what lobby

**Comment by Kesomannen** [comment]
I'm just using the `GetCurrentRtt` API on the NGO transport. I think the game specifically uses the Facepunch transport, so I'd check there if you're looking for the implementation

**Comment by CoolLKKPS** [comment]
uh so i join other people lobbies, i always got 0ms, i just confuse about that, in my knowledge u cannot ping UDP connection, and i didn't use steam relay to connect other people lobby

**Comment by Kesomannen** [comment]
I don't know why that is happening, sorry. The facepunch transport might be doing something other than a straight up ping, idk.

**Comment by CoolLKKPS** [comment]
its ok, don't mind
sug just make this mod send packet to other and let other reply that packet
